{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='metricsInstance', url='', help='"MetricsInstance controls an individual Metrics instance within a Grafana Agent deployment."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of MetricsInstance', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'monitoring.grafana.com/v1alpha1',
    kind: 'MetricsInstance',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"Spec holds the specification of the desired behavior for the Metrics instance."'),
  spec: {
    '#additionalScrapeConfigs':: d.obj(help='"AdditionalScrapeConfigs allows specifying a key of a Secret containing additional Grafana Agent Prometheus scrape configurations. SCrape configurations specified are appended to the configurations generated by the Grafana Agent Operator. Job configurations specified must have the form as specified in the official Prometheus documentation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config. As scrape configs are appended, the user is responsible to make sure it is valid. Note that using this feature may expose the possibility to break upgrades of Grafana Agent. It is advised to review both Grafana Agent and Prometheus release notes to ensure that no incompatible scrape configs are going to break Grafana Agent after the upgrade."'),
    additionalScrapeConfigs: {
      '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
      withKey(key): { spec+: { additionalScrapeConfigs+: { key: key } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { additionalScrapeConfigs+: { name: name } } },
      '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
      withOptional(optional): { spec+: { additionalScrapeConfigs+: { optional: optional } } },
    },
    '#podMonitorNamespaceSelector':: d.obj(help='"PodMonitorNamespaceSelector are the set of labels to determine which namespaces to watch for PodMonitor discovery. If nil, only checks own namespace."'),
    podMonitorNamespaceSelector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { podMonitorNamespaceSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { podMonitorNamespaceSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { podMonitorNamespaceSelector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { podMonitorNamespaceSelector+: { matchLabels+: matchLabels } } },
    },
    '#podMonitorSelector':: d.obj(help='"PodMonitorSelector determines which PodMonitors should be selected for target discovery. Experimental."'),
    podMonitorSelector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { podMonitorSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { podMonitorSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { podMonitorSelector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { podMonitorSelector+: { matchLabels+: matchLabels } } },
    },
    '#probeNamespaceSelector':: d.obj(help='"ProbeNamespaceSelector are the set of labels to determine which namespaces to watch for Probe discovery. If nil, only checks own namespace."'),
    probeNamespaceSelector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { probeNamespaceSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { probeNamespaceSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { probeNamespaceSelector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { probeNamespaceSelector+: { matchLabels+: matchLabels } } },
    },
    '#probeSelector':: d.obj(help='"ProbeSelector determines which Probes should be selected for target discovery."'),
    probeSelector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { probeSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { probeSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { probeSelector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { probeSelector+: { matchLabels+: matchLabels } } },
    },
    '#remoteWrite':: d.obj(help='"RemoteWrite controls remote_write settings for this instance."'),
    remoteWrite: {
      '#basicAuth':: d.obj(help='"BasicAuth for the URL."'),
      basicAuth: {
        '#password':: d.obj(help='"The secret in the service monitor namespace that contains the password for authentication."'),
        password: {
          '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { basicAuth+: { password+: { key: key } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { basicAuth+: { password+: { name: name } } },
          '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { basicAuth+: { password+: { optional: optional } } },
        },
        '#username':: d.obj(help='"The secret in the service monitor namespace that contains the username for authentication."'),
        username: {
          '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { basicAuth+: { username+: { key: key } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { basicAuth+: { username+: { name: name } } },
          '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { basicAuth+: { username+: { optional: optional } } },
        },
      },
      '#metadataConfig':: d.obj(help='"MetadataConfig configures the sending of series metadata to remote storage."'),
      metadataConfig: {
        '#withSend':: d.fn(help='"Send enables metric metadata to be sent to remote storage."', args=[d.arg(name='send', type=d.T.boolean)]),
        withSend(send): { metadataConfig+: { send: send } },
        '#withSendInterval':: d.fn(help='"SendInterval controls how frequently metric metadata is sent to remote storage."', args=[d.arg(name='sendInterval', type=d.T.string)]),
        withSendInterval(sendInterval): { metadataConfig+: { sendInterval: sendInterval } },
      },
      '#oauth2':: d.obj(help='"Oauth2 for URL"'),
      oauth2: {
        '#clientId':: d.obj(help='"The secret or configmap containing the OAuth2 client id"'),
        clientId: {
          '#configMap':: d.obj(help='"ConfigMap containing data to use for the targets."'),
          configMap: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { oauth2+: { clientId+: { configMap+: { key: key } } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { oauth2+: { clientId+: { configMap+: { name: name } } } },
            '#withOptional':: d.fn(help='"Specify whether the ConfigMap or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
            withOptional(optional): { oauth2+: { clientId+: { configMap+: { optional: optional } } } },
          },
          '#secret':: d.obj(help='"Secret containing data to use for the targets."'),
          secret: {
            '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { oauth2+: { clientId+: { secret+: { key: key } } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { oauth2+: { clientId+: { secret+: { name: name } } } },
            '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
            withOptional(optional): { oauth2+: { clientId+: { secret+: { optional: optional } } } },
          },
        },
        '#clientSecret':: d.obj(help='"The secret containing the OAuth2 client secret"'),
        clientSecret: {
          '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { oauth2+: { clientSecret+: { key: key } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { oauth2+: { clientSecret+: { name: name } } },
          '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { oauth2+: { clientSecret+: { optional: optional } } },
        },
        '#withEndpointParams':: d.fn(help='"Parameters to append to the token URL"', args=[d.arg(name='endpointParams', type=d.T.object)]),
        withEndpointParams(endpointParams): { oauth2+: { endpointParams: endpointParams } },
        '#withEndpointParamsMixin':: d.fn(help='"Parameters to append to the token URL"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='endpointParams', type=d.T.object)]),
        withEndpointParamsMixin(endpointParams): { oauth2+: { endpointParams+: endpointParams } },
        '#withScopes':: d.fn(help='"OAuth2 scopes used for the token request"', args=[d.arg(name='scopes', type=d.T.array)]),
        withScopes(scopes): { oauth2+: { scopes: if std.isArray(v=scopes) then scopes else [scopes] } },
        '#withScopesMixin':: d.fn(help='"OAuth2 scopes used for the token request"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopes', type=d.T.array)]),
        withScopesMixin(scopes): { oauth2+: { scopes+: if std.isArray(v=scopes) then scopes else [scopes] } },
        '#withTokenUrl':: d.fn(help='"The URL to fetch the token from"', args=[d.arg(name='tokenUrl', type=d.T.string)]),
        withTokenUrl(tokenUrl): { oauth2+: { tokenUrl: tokenUrl } },
      },
      '#queueConfig':: d.obj(help='"QueueConfig allows tuning of the remote_write queue parameters."'),
      queueConfig: {
        '#withBatchSendDeadline':: d.fn(help='"BatchSendDeadline is the maximum time a sample will wait in buffer."', args=[d.arg(name='batchSendDeadline', type=d.T.string)]),
        withBatchSendDeadline(batchSendDeadline): { queueConfig+: { batchSendDeadline: batchSendDeadline } },
        '#withCapacity':: d.fn(help='"Capacity is the number of samples to buffer per shard before we start dropping them."', args=[d.arg(name='capacity', type=d.T.integer)]),
        withCapacity(capacity): { queueConfig+: { capacity: capacity } },
        '#withMaxBackoff':: d.fn(help='"MaxBackoff is the maximum retry delay."', args=[d.arg(name='maxBackoff', type=d.T.string)]),
        withMaxBackoff(maxBackoff): { queueConfig+: { maxBackoff: maxBackoff } },
        '#withMaxRetries':: d.fn(help='"MaxRetries is the maximum number of times to retry a batch on recoverable errors."', args=[d.arg(name='maxRetries', type=d.T.integer)]),
        withMaxRetries(maxRetries): { queueConfig+: { maxRetries: maxRetries } },
        '#withMaxSamplesPerSend':: d.fn(help='"MaxSamplesPerSend is the maximum number of samples per send."', args=[d.arg(name='maxSamplesPerSend', type=d.T.integer)]),
        withMaxSamplesPerSend(maxSamplesPerSend): { queueConfig+: { maxSamplesPerSend: maxSamplesPerSend } },
        '#withMaxShards':: d.fn(help='"MaxShards is the maximum number of shards, i.e. amount of concurrency."', args=[d.arg(name='maxShards', type=d.T.integer)]),
        withMaxShards(maxShards): { queueConfig+: { maxShards: maxShards } },
        '#withMinBackoff':: d.fn(help='"MinBackoff is the initial retry delay. Gets doubled for every retry."', args=[d.arg(name='minBackoff', type=d.T.string)]),
        withMinBackoff(minBackoff): { queueConfig+: { minBackoff: minBackoff } },
        '#withMinShards':: d.fn(help='"MinShards is the minimum number of shards, i.e. amount of concurrency."', args=[d.arg(name='minShards', type=d.T.integer)]),
        withMinShards(minShards): { queueConfig+: { minShards: minShards } },
        '#withRetryOnRateLimit':: d.fn(help='"RetryOnRateLimit retries requests when encountering rate limits."', args=[d.arg(name='retryOnRateLimit', type=d.T.boolean)]),
        withRetryOnRateLimit(retryOnRateLimit): { queueConfig+: { retryOnRateLimit: retryOnRateLimit } },
      },
      '#sigv4':: d.obj(help='"SigV4 configures SigV4-based authentication to the remote_write endpoint. Will be used if SigV4 is defined, even with an empty object."'),
      sigv4: {
        '#accessKey':: d.obj(help='"AccessKey holds the secret of the AWS API access key to use for signing. If not provided, The environment variable AWS_ACCESS_KEY_ID is used."'),
        accessKey: {
          '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { sigv4+: { accessKey+: { key: key } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { sigv4+: { accessKey+: { name: name } } },
          '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { sigv4+: { accessKey+: { optional: optional } } },
        },
        '#secretKey':: d.obj(help='"SecretKey of the AWS API to use for signing. If blank, the environment variable AWS_SECRET_ACCESS_KEY is used."'),
        secretKey: {
          '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { sigv4+: { secretKey+: { key: key } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { sigv4+: { secretKey+: { name: name } } },
          '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { sigv4+: { secretKey+: { optional: optional } } },
        },
        '#withProfile':: d.fn(help='"Profile is the named AWS profile to use for authentication."', args=[d.arg(name='profile', type=d.T.string)]),
        withProfile(profile): { sigv4+: { profile: profile } },
        '#withRegion':: d.fn(help='"Region of the AWS endpoint. If blank, the region from the default credentials chain is used."', args=[d.arg(name='region', type=d.T.string)]),
        withRegion(region): { sigv4+: { region: region } },
        '#withRoleARN':: d.fn(help='"RoleARN is the AWS Role ARN to use for authentication, as an alternative for using the AWS API keys."', args=[d.arg(name='roleARN', type=d.T.string)]),
        withRoleARN(roleARN): { sigv4+: { roleARN: roleARN } },
      },
      '#tlsConfig':: d.obj(help='"TLSConfig to use for remote_write."'),
      tlsConfig: {
        '#ca':: d.obj(help='"Struct containing the CA cert to use for the targets."'),
        ca: {
          '#configMap':: d.obj(help='"ConfigMap containing data to use for the targets."'),
          configMap: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { tlsConfig+: { ca+: { configMap+: { key: key } } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { tlsConfig+: { ca+: { configMap+: { name: name } } } },
            '#withOptional':: d.fn(help='"Specify whether the ConfigMap or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
            withOptional(optional): { tlsConfig+: { ca+: { configMap+: { optional: optional } } } },
          },
          '#secret':: d.obj(help='"Secret containing data to use for the targets."'),
          secret: {
            '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { tlsConfig+: { ca+: { secret+: { key: key } } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { tlsConfig+: { ca+: { secret+: { name: name } } } },
            '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
            withOptional(optional): { tlsConfig+: { ca+: { secret+: { optional: optional } } } },
          },
        },
        '#cert':: d.obj(help='"Struct containing the client cert file for the targets."'),
        cert: {
          '#configMap':: d.obj(help='"ConfigMap containing data to use for the targets."'),
          configMap: {
            '#withKey':: d.fn(help='"The key to select."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { tlsConfig+: { cert+: { configMap+: { key: key } } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { tlsConfig+: { cert+: { configMap+: { name: name } } } },
            '#withOptional':: d.fn(help='"Specify whether the ConfigMap or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
            withOptional(optional): { tlsConfig+: { cert+: { configMap+: { optional: optional } } } },
          },
          '#secret':: d.obj(help='"Secret containing data to use for the targets."'),
          secret: {
            '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { tlsConfig+: { cert+: { secret+: { key: key } } } },
            '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { tlsConfig+: { cert+: { secret+: { name: name } } } },
            '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
            withOptional(optional): { tlsConfig+: { cert+: { secret+: { optional: optional } } } },
          },
        },
        '#keySecret':: d.obj(help='"Secret containing the client key file for the targets."'),
        keySecret: {
          '#withKey':: d.fn(help='"The key of the secret to select from.  Must be a valid secret key."', args=[d.arg(name='key', type=d.T.string)]),
          withKey(key): { tlsConfig+: { keySecret+: { key: key } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { tlsConfig+: { keySecret+: { name: name } } },
          '#withOptional':: d.fn(help='"Specify whether the Secret or its key must be defined"', args=[d.arg(name='optional', type=d.T.boolean)]),
          withOptional(optional): { tlsConfig+: { keySecret+: { optional: optional } } },
        },
        '#withCaFile':: d.fn(help='"Path to the CA cert in the Prometheus container to use for the targets."', args=[d.arg(name='caFile', type=d.T.string)]),
        withCaFile(caFile): { tlsConfig+: { caFile: caFile } },
        '#withCertFile':: d.fn(help='"Path to the client cert file in the Prometheus container for the targets."', args=[d.arg(name='certFile', type=d.T.string)]),
        withCertFile(certFile): { tlsConfig+: { certFile: certFile } },
        '#withInsecureSkipVerify':: d.fn(help='"Disable target certificate validation."', args=[d.arg(name='insecureSkipVerify', type=d.T.boolean)]),
        withInsecureSkipVerify(insecureSkipVerify): { tlsConfig+: { insecureSkipVerify: insecureSkipVerify } },
        '#withKeyFile':: d.fn(help='"Path to the client key file in the Prometheus container for the targets."', args=[d.arg(name='keyFile', type=d.T.string)]),
        withKeyFile(keyFile): { tlsConfig+: { keyFile: keyFile } },
        '#withServerName':: d.fn(help='"Used to verify the hostname for the targets."', args=[d.arg(name='serverName', type=d.T.string)]),
        withServerName(serverName): { tlsConfig+: { serverName: serverName } },
      },
      '#withBearerToken':: d.fn(help='"BearerToken used for remote_write."', args=[d.arg(name='bearerToken', type=d.T.string)]),
      withBearerToken(bearerToken): { bearerToken: bearerToken },
      '#withBearerTokenFile':: d.fn(help='"BearerTokenFile used to read bearer token."', args=[d.arg(name='bearerTokenFile', type=d.T.string)]),
      withBearerTokenFile(bearerTokenFile): { bearerTokenFile: bearerTokenFile },
      '#withHeaders':: d.fn(help="\"Headers is a set of custom HTTP headers to be sent along with each remote_write request. Be aware that any headers set by Grafana Agent itself can't be overwritten.\"", args=[d.arg(name='headers', type=d.T.object)]),
      withHeaders(headers): { headers: headers },
      '#withHeadersMixin':: d.fn(help="\"Headers is a set of custom HTTP headers to be sent along with each remote_write request. Be aware that any headers set by Grafana Agent itself can't be overwritten.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='headers', type=d.T.object)]),
      withHeadersMixin(headers): { headers+: headers },
      '#withName':: d.fn(help='"Name of the remote_write queue. Must be unique if specified. The name is used in metrics and logging in order to differentiate queues."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withProxyUrl':: d.fn(help='"ProxyURL to proxy requests through. Optional."', args=[d.arg(name='proxyUrl', type=d.T.string)]),
      withProxyUrl(proxyUrl): { proxyUrl: proxyUrl },
      '#withRemoteTimeout':: d.fn(help='"RemoteTimeout is the timeout for requests to the remote_write endpoint."', args=[d.arg(name='remoteTimeout', type=d.T.string)]),
      withRemoteTimeout(remoteTimeout): { remoteTimeout: remoteTimeout },
      '#withUrl':: d.fn(help='"URL of the endpoint to send samples to."', args=[d.arg(name='url', type=d.T.string)]),
      withUrl(url): { url: url },
      '#withWriteRelabelConfigs':: d.fn(help='"WriteRelabelConfigs holds relabel_configs to relabel samples before they are sent to the remote_write endpoint."', args=[d.arg(name='writeRelabelConfigs', type=d.T.array)]),
      withWriteRelabelConfigs(writeRelabelConfigs): { writeRelabelConfigs: if std.isArray(v=writeRelabelConfigs) then writeRelabelConfigs else [writeRelabelConfigs] },
      '#withWriteRelabelConfigsMixin':: d.fn(help='"WriteRelabelConfigs holds relabel_configs to relabel samples before they are sent to the remote_write endpoint."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='writeRelabelConfigs', type=d.T.array)]),
      withWriteRelabelConfigsMixin(writeRelabelConfigs): { writeRelabelConfigs+: if std.isArray(v=writeRelabelConfigs) then writeRelabelConfigs else [writeRelabelConfigs] },
      '#writeRelabelConfigs':: d.obj(help='"WriteRelabelConfigs holds relabel_configs to relabel samples before they are sent to the remote_write endpoint."'),
      writeRelabelConfigs: {
        '#withAction':: d.fn(help="\"Action to perform based on regex matching. Default is 'replace'\"", args=[d.arg(name='action', type=d.T.string)]),
        withAction(action): { action: action },
        '#withModulus':: d.fn(help='"Modulus to take of the hash of the source label values."', args=[d.arg(name='modulus', type=d.T.integer)]),
        withModulus(modulus): { modulus: modulus },
        '#withRegex':: d.fn(help="\"Regular expression against which the extracted value is matched. Default is '(.*)'\"", args=[d.arg(name='regex', type=d.T.string)]),
        withRegex(regex): { regex: regex },
        '#withReplacement':: d.fn(help="\"Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'\"", args=[d.arg(name='replacement', type=d.T.string)]),
        withReplacement(replacement): { replacement: replacement },
        '#withSeparator':: d.fn(help="\"Separator placed between concatenated source label values. default is ';'.\"", args=[d.arg(name='separator', type=d.T.string)]),
        withSeparator(separator): { separator: separator },
        '#withSourceLabels':: d.fn(help='"The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions."', args=[d.arg(name='sourceLabels', type=d.T.array)]),
        withSourceLabels(sourceLabels): { sourceLabels: if std.isArray(v=sourceLabels) then sourceLabels else [sourceLabels] },
        '#withSourceLabelsMixin':: d.fn(help='"The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sourceLabels', type=d.T.array)]),
        withSourceLabelsMixin(sourceLabels): { sourceLabels+: if std.isArray(v=sourceLabels) then sourceLabels else [sourceLabels] },
        '#withTargetLabel':: d.fn(help='"Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available."', args=[d.arg(name='targetLabel', type=d.T.string)]),
        withTargetLabel(targetLabel): { targetLabel: targetLabel },
      },
    },
    '#serviceMonitorNamespaceSelector':: d.obj(help='"ServiceMonitorNamespaceSelector are the set of labels to determine which namespaces to watch for ServiceMonitor discovery. If nil, only checks own namespace."'),
    serviceMonitorNamespaceSelector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { serviceMonitorNamespaceSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { serviceMonitorNamespaceSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { serviceMonitorNamespaceSelector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { serviceMonitorNamespaceSelector+: { matchLabels+: matchLabels } } },
    },
    '#serviceMonitorSelector':: d.obj(help='"ServiceMonitorSelector determines which ServiceMonitors should be selected for target discovery."'),
    serviceMonitorSelector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { serviceMonitorSelector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { serviceMonitorSelector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { serviceMonitorSelector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { serviceMonitorSelector+: { matchLabels+: matchLabels } } },
    },
    '#withMaxWALTime':: d.fn(help='"MaxWALTime is the maximum amount of time series and asmples may exist in the WAL before being forcibly deleted."', args=[d.arg(name='maxWALTime', type=d.T.string)]),
    withMaxWALTime(maxWALTime): { spec+: { maxWALTime: maxWALTime } },
    '#withMinWALTime':: d.fn(help='"MinWALTime is the minimum amount of time series and samples may exist in the WAL before being considered for deletion."', args=[d.arg(name='minWALTime', type=d.T.string)]),
    withMinWALTime(minWALTime): { spec+: { minWALTime: minWALTime } },
    '#withRemoteFlushDeadline':: d.fn(help='"RemoteFlushDeadline is the deadline for flushing data when an instance shuts down."', args=[d.arg(name='remoteFlushDeadline', type=d.T.string)]),
    withRemoteFlushDeadline(remoteFlushDeadline): { spec+: { remoteFlushDeadline: remoteFlushDeadline } },
    '#withRemoteWrite':: d.fn(help='"RemoteWrite controls remote_write settings for this instance."', args=[d.arg(name='remoteWrite', type=d.T.array)]),
    withRemoteWrite(remoteWrite): { spec+: { remoteWrite: if std.isArray(v=remoteWrite) then remoteWrite else [remoteWrite] } },
    '#withRemoteWriteMixin':: d.fn(help='"RemoteWrite controls remote_write settings for this instance."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remoteWrite', type=d.T.array)]),
    withRemoteWriteMixin(remoteWrite): { spec+: { remoteWrite+: if std.isArray(v=remoteWrite) then remoteWrite else [remoteWrite] } },
    '#withWalTruncateFrequency':: d.fn(help='"WALTruncateFrequency specifies how frequently the WAL truncation process should run. Higher values causes the WAL to increase and for old series to stay in the WAL for longer, but reduces the chances of data loss when remote_write is failing for longer than the given frequency."', args=[d.arg(name='walTruncateFrequency', type=d.T.string)]),
    withWalTruncateFrequency(walTruncateFrequency): { spec+: { walTruncateFrequency: walTruncateFrequency } },
    '#withWriteStaleOnShutdown':: d.fn(help='"WriteStaleOnShutdown writes staleness markers on shutdown for all series."', args=[d.arg(name='writeStaleOnShutdown', type=d.T.boolean)]),
    withWriteStaleOnShutdown(writeStaleOnShutdown): { spec+: { writeStaleOnShutdown: writeStaleOnShutdown } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
