{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='podLogs', url='', help='"PodLogs defines how to collect logs for a pod."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of PodLogs', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'monitoring.grafana.com/v1alpha1',
    kind: 'PodLogs',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"Spec holds the specification of the desired behavior for the PodLogs."'),
  spec: {
    '#namespaceSelector':: d.obj(help='"Selector to select which namespaces the Pod objects are discovered from."'),
    namespaceSelector: {
      '#withAny':: d.fn(help='"Boolean describing whether all namespaces are selected in contrast to a list restricting them."', args=[d.arg(name='any', type=d.T.boolean)]),
      withAny(any): { spec+: { namespaceSelector+: { any: any } } },
      '#withMatchNames':: d.fn(help='"List of namespace names to select from."', args=[d.arg(name='matchNames', type=d.T.array)]),
      withMatchNames(matchNames): { spec+: { namespaceSelector+: { matchNames: if std.isArray(v=matchNames) then matchNames else [matchNames] } } },
      '#withMatchNamesMixin':: d.fn(help='"List of namespace names to select from."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchNames', type=d.T.array)]),
      withMatchNamesMixin(matchNames): { spec+: { namespaceSelector+: { matchNames+: if std.isArray(v=matchNames) then matchNames else [matchNames] } } },
    },
    '#pipelineStages':: d.obj(help='"Pipeline stages for this pod. Pipeline stages support transforming and filtering log lines."'),
    pipelineStages: {
      '#drop':: d.obj(help='"Drop is a filtering stage that lets you drop certain logs."'),
      drop: {
        '#withDropCounterReason':: d.fn(help='"Every time a log line is dropped, the metric logentry_dropped_lines_total is incremented. A \\"reason\\" label is added, and can be customized by providing a custom value here. Defaults to \\"drop_stage\\"."', args=[d.arg(name='dropCounterReason', type=d.T.string)]),
        withDropCounterReason(dropCounterReason): { drop+: { dropCounterReason: dropCounterReason } },
        '#withExpression':: d.fn(help='"RE2 regular expression. \\n If source is provided, the regex attempts to match the source. \\n If no source is provided, then the regex attempts to attach the log line. \\n If the provided regex matches the log line or a provided source, the line is dropped."', args=[d.arg(name='expression', type=d.T.string)]),
        withExpression(expression): { drop+: { expression: expression } },
        '#withLongerThan':: d.fn(help='"LongerThan will drop a log line if it its content is longer than this value (in bytes). Can be expressed as an integer (8192) or a number with a suffix (8kb)."', args=[d.arg(name='longerThan', type=d.T.string)]),
        withLongerThan(longerThan): { drop+: { longerThan: longerThan } },
        '#withOlderThan':: d.fn(help="\"OlderThan will be parsed as a Go duration. If the log line's timestamp is older than the current time minus the provided duration, it will be dropped.\"", args=[d.arg(name='olderThan', type=d.T.string)]),
        withOlderThan(olderThan): { drop+: { olderThan: olderThan } },
        '#withSource':: d.fn(help='"Name from the extract data to parse. If empty, uses the log message."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { drop+: { source: source } },
        '#withValue':: d.fn(help='"Value can only be specified when source is specified. If the value provided is an exact match for the given source then the line will be dropped. \\n Mutually exclusive with expression."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { drop+: { value: value } },
      },
      '#json':: d.obj(help='"JSON is a parsing stage that reads the log line as JSON and accepts JMESPath expressions to extract data. \\n Information on JMESPath: http://jmespath.org/"'),
      json: {
        '#withExpressions':: d.fn(help='"Set of the key/value pairs of JMESPath expressions. The key will be the key in the extracted data while the expression will be the value, evaluated as a JMESPath from the source data. \\n Literal JMESPath expressions can be used by wrapping a key in double quotes, which then must be wrapped again in single quotes in YAML so they get passed to the JMESPath parser."', args=[d.arg(name='expressions', type=d.T.object)]),
        withExpressions(expressions): { json+: { expressions: expressions } },
        '#withExpressionsMixin':: d.fn(help='"Set of the key/value pairs of JMESPath expressions. The key will be the key in the extracted data while the expression will be the value, evaluated as a JMESPath from the source data. \\n Literal JMESPath expressions can be used by wrapping a key in double quotes, which then must be wrapped again in single quotes in YAML so they get passed to the JMESPath parser."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='expressions', type=d.T.object)]),
        withExpressionsMixin(expressions): { json+: { expressions+: expressions } },
        '#withSource':: d.fn(help='"Name from the extracted data to parse as JSON. If empty, uses entire log message."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { json+: { source: source } },
      },
      '#match':: d.obj(help='"Match is a filtering stage that conditionally applies a set of stages or drop entries when a log entry matches a configurable LogQL stream selector and filter expressions."'),
      match: {
        '#withAction':: d.fn(help='"Determines what action is taken when the selector matches the log line. Can be keep or drop. Defaults to keep. When set to drop, entries are dropped and no later metrics are recorded. Stages must be empty when dropping metrics."', args=[d.arg(name='action', type=d.T.string)]),
        withAction(action): { match+: { action: action } },
        '#withDropCounterReason':: d.fn(help='"Every time a log line is dropped, the metric logentry_dropped_lines_total is incremented. A \\"reason\\" label is added, and can be customized by providing a custom value here. Defaults to \\"match_stage.\\', args=[d.arg(name='dropCounterReason', type=d.T.string)]),
        withDropCounterReason(dropCounterReason): { match+: { dropCounterReason: dropCounterReason } },
        '#withPipelineName':: d.fn(help='"Names the pipeline. When defined, creates an additional label in the pipeline_duration_seconds histogram, where the value is concatenated with job_name using an underscore."', args=[d.arg(name='pipelineName', type=d.T.string)]),
        withPipelineName(pipelineName): { match+: { pipelineName: pipelineName } },
        '#withSelector':: d.fn(help='"LogQL stream selector and filter expressions. Required."', args=[d.arg(name='selector', type=d.T.string)]),
        withSelector(selector): { match+: { selector: selector } },
        '#withStages':: d.fn(help='"Nested set of pipeline stages to execute when action is keep and the log line matches selector. \\n An example value for stages may be: \\n stages: | - json: {} - labelAllow: [foo, bar] \\n Note that stages is a string because SIG API Machinery does not support recursive types, and so it cannot be validated for correctness. Be careful not to mistype anything."', args=[d.arg(name='stages', type=d.T.string)]),
        withStages(stages): { match+: { stages: stages } },
      },
      '#multiline':: d.obj(help='"Multiline stage merges multiple lines into a multiline block before passing it on to the next stage in the pipeline."'),
      multiline: {
        '#withFirstLine':: d.fn(help='"RE2 regular expression. Creates a new multiline block when matched. Required."', args=[d.arg(name='firstLine', type=d.T.string)]),
        withFirstLine(firstLine): { multiline+: { firstLine: firstLine } },
        '#withMaxLines':: d.fn(help='"Maximum number of lines a block can have. A new block is started if the number of lines surpasses this value. Defaults to 128."', args=[d.arg(name='maxLines', type=d.T.integer)]),
        withMaxLines(maxLines): { multiline+: { maxLines: maxLines } },
        '#withMaxWaitTime':: d.fn(help='"Maximum time to wait before passing on the multiline block to the next stage if no new lines are received. Defaults to 3s."', args=[d.arg(name='maxWaitTime', type=d.T.string)]),
        withMaxWaitTime(maxWaitTime): { multiline+: { maxWaitTime: maxWaitTime } },
      },
      '#output':: d.obj(help='"Output stage is an action stage that takes data from the extracted map and changes the log line that will be sent to Loki."'),
      output: {
        '#withSource':: d.fn(help='"Name from extract data to use for the log entry. Required."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { output+: { source: source } },
      },
      '#pack':: d.obj(help='"Pack is a transform stage that lets you embed extracted values and labels into the log line by packing the log line and labels inside of a JSON object."'),
      pack: {
        '#withIngestTimestamp':: d.fn(help='"If the resulting log line should use any existing timestamp or use time.Now() when the line was created. Set to true when combining several log streams from different containers to avoid out of order errors."', args=[d.arg(name='ingestTimestamp', type=d.T.boolean)]),
        withIngestTimestamp(ingestTimestamp): { pack+: { ingestTimestamp: ingestTimestamp } },
        '#withLabels':: d.fn(help='"Name from extracted data or line labels. Required. Labels provided here are automatically removed from output labels."', args=[d.arg(name='labels', type=d.T.array)]),
        withLabels(labels): { pack+: { labels: if std.isArray(v=labels) then labels else [labels] } },
        '#withLabelsMixin':: d.fn(help='"Name from extracted data or line labels. Required. Labels provided here are automatically removed from output labels."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.array)]),
        withLabelsMixin(labels): { pack+: { labels+: if std.isArray(v=labels) then labels else [labels] } },
      },
      '#regex':: d.obj(help='"Regex is a parsing stage that parses a log line using a regular expression.  Named capture groups in the regex allows for adding data into the extracted map."'),
      regex: {
        '#withExpression':: d.fn(help='"RE2 regular expression. Each capture group MUST be named. Required."', args=[d.arg(name='expression', type=d.T.string)]),
        withExpression(expression): { regex+: { expression: expression } },
        '#withSource':: d.fn(help='"Name from extracted data to parse. If empty, defaults to using the log message."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { regex+: { source: source } },
      },
      '#replace':: d.obj(help='"Replace is a parsing stage that parses a log line using a regular expression and replaces the log line. Named capture groups in the regex allows for adding data into the extracted map."'),
      replace: {
        '#withExpression':: d.fn(help='"RE2 regular expression. Each capture group MUST be named. Required."', args=[d.arg(name='expression', type=d.T.string)]),
        withExpression(expression): { replace+: { expression: expression } },
        '#withReplace':: d.fn(help='"Value to replace the captured group with."', args=[d.arg(name='replace', type=d.T.string)]),
        withReplace(replace): { replace+: { replace: replace } },
        '#withSource':: d.fn(help='"Name from extracted data to parse. If empty, defaults to using the log message."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { replace+: { source: source } },
      },
      '#template':: d.obj(help="\"Template is a transform stage that manipulates the values in the extracted map using Go's template syntax.\""),
      template: {
        '#withSource':: d.fn(help='"Name from extracted data to parse. Required. If empty, defaults to using the log message."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { template+: { source: source } },
        '#withTemplate':: d.fn(help='"Go template string to use. Required. In addition to normal template functions, ToLower, ToUpper, Replace, Trim, TrimLeft, TrimRight, TrimPrefix, and TrimSpace are also available."', args=[d.arg(name='template', type=d.T.string)]),
        withTemplate(template): { template+: { template: template } },
      },
      '#tenant':: d.obj(help='"Tenant is an action stage that sets the tenant ID for the log entry picking it from a field in the extracted data map. If the field is missing, the default LogsClientSpec.tenantId will be used."'),
      tenant: {
        '#withLabel':: d.fn(help='"Name from labels whose value should be set as tenant ID. Mutually exclusive with source and value."', args=[d.arg(name='label', type=d.T.string)]),
        withLabel(label): { tenant+: { label: label } },
        '#withSource':: d.fn(help='"Name from extracted data to use as the tenant ID. Mutually exclusive with label and value."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { tenant+: { source: source } },
        '#withValue':: d.fn(help='"Value to use for the template ID. Useful when this stage is used within a conditional pipeline such as match. Mutually exclusive with label and source."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { tenant+: { value: value } },
      },
      '#timestamp':: d.obj(help='"Timestamp is an action stage that can change the timestamp of a log line before it is sent to Loki. If not present, the timestamp of a log line defaults to the time when the log line was read."'),
      timestamp: {
        '#withActionOnFailure':: d.fn(help="\"Action to take when the timestamp can't be extracted or parsed. Can be skip or fudge. Defaults to fudge.\"", args=[d.arg(name='actionOnFailure', type=d.T.string)]),
        withActionOnFailure(actionOnFailure): { timestamp+: { actionOnFailure: actionOnFailure } },
        '#withFallbackFormats':: d.fn(help='"Fallback formats to try if format fails."', args=[d.arg(name='fallbackFormats', type=d.T.array)]),
        withFallbackFormats(fallbackFormats): { timestamp+: { fallbackFormats: if std.isArray(v=fallbackFormats) then fallbackFormats else [fallbackFormats] } },
        '#withFallbackFormatsMixin':: d.fn(help='"Fallback formats to try if format fails."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='fallbackFormats', type=d.T.array)]),
        withFallbackFormatsMixin(fallbackFormats): { timestamp+: { fallbackFormats+: if std.isArray(v=fallbackFormats) then fallbackFormats else [fallbackFormats] } },
        '#withFormat':: d.fn(help='"Determines format of the time string. Required. Can be one of: ANSIC, UnixDate, RubyDate, RFC822, RFC822Z, RFC850, RFC1123, RFC1123Z, RFC3339, RFC3339Nano, Unix, UnixMs, UnixUs, UnixNs."', args=[d.arg(name='format', type=d.T.string)]),
        withFormat(format): { timestamp+: { format: format } },
        '#withLocation':: d.fn(help='"IANA Timezone Database string."', args=[d.arg(name='location', type=d.T.string)]),
        withLocation(location): { timestamp+: { location: location } },
        '#withSource':: d.fn(help='"Name from extracted data to use as the timestamp. Required."', args=[d.arg(name='source', type=d.T.string)]),
        withSource(source): { timestamp+: { source: source } },
      },
      '#withCri':: d.fn(help='"CRI is a parsing stage that reads log lines using the standard CRI logging format. Supply cri: {} to enable."', args=[d.arg(name='cri', type=d.T.object)]),
      withCri(cri): { cri: cri },
      '#withCriMixin':: d.fn(help='"CRI is a parsing stage that reads log lines using the standard CRI logging format. Supply cri: {} to enable."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='cri', type=d.T.object)]),
      withCriMixin(cri): { cri+: cri },
      '#withDocker':: d.fn(help='"Docker is a parsing stage that reads log lines using the standard Docker logging format. Supply docker: {} to enable."', args=[d.arg(name='docker', type=d.T.object)]),
      withDocker(docker): { docker: docker },
      '#withDockerMixin':: d.fn(help='"Docker is a parsing stage that reads log lines using the standard Docker logging format. Supply docker: {} to enable."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='docker', type=d.T.object)]),
      withDockerMixin(docker): { docker+: docker },
      '#withLabelAllow':: d.fn(help='"LabelAllow is an action stage that only allows the provided labels to be included in the label set that is sent to Loki with the log entry."', args=[d.arg(name='labelAllow', type=d.T.array)]),
      withLabelAllow(labelAllow): { labelAllow: if std.isArray(v=labelAllow) then labelAllow else [labelAllow] },
      '#withLabelAllowMixin':: d.fn(help='"LabelAllow is an action stage that only allows the provided labels to be included in the label set that is sent to Loki with the log entry."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labelAllow', type=d.T.array)]),
      withLabelAllowMixin(labelAllow): { labelAllow+: if std.isArray(v=labelAllow) then labelAllow else [labelAllow] },
      '#withLabelDrop':: d.fn(help='"LabelDrop is an action stage that drops labels from the label set that is sent to Loki with the log entry."', args=[d.arg(name='labelDrop', type=d.T.array)]),
      withLabelDrop(labelDrop): { labelDrop: if std.isArray(v=labelDrop) then labelDrop else [labelDrop] },
      '#withLabelDropMixin':: d.fn(help='"LabelDrop is an action stage that drops labels from the label set that is sent to Loki with the log entry."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labelDrop', type=d.T.array)]),
      withLabelDropMixin(labelDrop): { labelDrop+: if std.isArray(v=labelDrop) then labelDrop else [labelDrop] },
      '#withLabels':: d.fn(help='"Labels is an action stage that takes data from the extracted map and modifies the label set that is sent to Loki with the log entry. \\n The key is REQUIRED and represents the name for the label that will be created. Value is optional and will be the name from extracted data to use for the value of the label. If the value is not provided, it defaults to match the key."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { labels: labels },
      '#withLabelsMixin':: d.fn(help='"Labels is an action stage that takes data from the extracted map and modifies the label set that is sent to Loki with the log entry. \\n The key is REQUIRED and represents the name for the label that will be created. Value is optional and will be the name from extracted data to use for the value of the label. If the value is not provided, it defaults to match the key."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { labels+: labels },
      '#withMetrics':: d.fn(help='"Metrics is an action stage that supports defining and updating metrics based on data from the extracted map. Created metrics are not pushed to Loki or Prometheus and are instead exposed via the /metrics endpoint of the Grafana Agent pod. The Grafana Agent Operator should be configured with a MetricsInstance that discovers the logging DaemonSet to collect metrics created by this stage."', args=[d.arg(name='metrics', type=d.T.object)]),
      withMetrics(metrics): { metrics: metrics },
      '#withMetricsMixin':: d.fn(help='"Metrics is an action stage that supports defining and updating metrics based on data from the extracted map. Created metrics are not pushed to Loki or Prometheus and are instead exposed via the /metrics endpoint of the Grafana Agent pod. The Grafana Agent Operator should be configured with a MetricsInstance that discovers the logging DaemonSet to collect metrics created by this stage."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metrics', type=d.T.object)]),
      withMetricsMixin(metrics): { metrics+: metrics },
    },
    '#relabelings':: d.obj(help='"RelabelConfigs to apply to logs before delivering. Grafana Agent Operator automatically adds relabelings for a few standard Kubernetes fields and replaces original scrape job name with __tmp_logs_job_name. \\n More info: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#relabel_configs"'),
    relabelings: {
      '#withAction':: d.fn(help="\"Action to perform based on regex matching. Default is 'replace'\"", args=[d.arg(name='action', type=d.T.string)]),
      withAction(action): { action: action },
      '#withModulus':: d.fn(help='"Modulus to take of the hash of the source label values."', args=[d.arg(name='modulus', type=d.T.integer)]),
      withModulus(modulus): { modulus: modulus },
      '#withRegex':: d.fn(help="\"Regular expression against which the extracted value is matched. Default is '(.*)'\"", args=[d.arg(name='regex', type=d.T.string)]),
      withRegex(regex): { regex: regex },
      '#withReplacement':: d.fn(help="\"Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available. Default is '$1'\"", args=[d.arg(name='replacement', type=d.T.string)]),
      withReplacement(replacement): { replacement: replacement },
      '#withSeparator':: d.fn(help="\"Separator placed between concatenated source label values. default is ';'.\"", args=[d.arg(name='separator', type=d.T.string)]),
      withSeparator(separator): { separator: separator },
      '#withSourceLabels':: d.fn(help='"The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions."', args=[d.arg(name='sourceLabels', type=d.T.array)]),
      withSourceLabels(sourceLabels): { sourceLabels: if std.isArray(v=sourceLabels) then sourceLabels else [sourceLabels] },
      '#withSourceLabelsMixin':: d.fn(help='"The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sourceLabels', type=d.T.array)]),
      withSourceLabelsMixin(sourceLabels): { sourceLabels+: if std.isArray(v=sourceLabels) then sourceLabels else [sourceLabels] },
      '#withTargetLabel':: d.fn(help='"Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available."', args=[d.arg(name='targetLabel', type=d.T.string)]),
      withTargetLabel(targetLabel): { targetLabel: targetLabel },
    },
    '#selector':: d.obj(help='"Selector to select Pod objects. Required."'),
    selector: {
      '#matchExpressions':: d.obj(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."'),
      matchExpressions: {
        '#withKey':: d.fn(help='"key is the label key that the selector applies to."', args=[d.arg(name='key', type=d.T.string)]),
        withKey(key): { key: key },
        '#withOperator':: d.fn(help="\"operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.\"", args=[d.arg(name='operator', type=d.T.string)]),
        withOperator(operator): { operator: operator },
        '#withValues':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."', args=[d.arg(name='values', type=d.T.array)]),
        withValues(values): { values: if std.isArray(v=values) then values else [values] },
        '#withValuesMixin':: d.fn(help='"values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='values', type=d.T.array)]),
        withValuesMixin(values): { values+: if std.isArray(v=values) then values else [values] },
      },
      '#withMatchExpressions':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressions(matchExpressions): { spec+: { selector+: { matchExpressions: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchExpressionsMixin':: d.fn(help='"matchExpressions is a list of label selector requirements. The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchExpressions', type=d.T.array)]),
      withMatchExpressionsMixin(matchExpressions): { spec+: { selector+: { matchExpressions+: if std.isArray(v=matchExpressions) then matchExpressions else [matchExpressions] } } },
      '#withMatchLabels':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { selector+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \\"key\\", the operator is \\"In\\", and the values array contains only \\"value\\". The requirements are ANDed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { selector+: { matchLabels+: matchLabels } } },
    },
    '#withJobLabel':: d.fn(help='"The label to use to retrieve the job name from."', args=[d.arg(name='jobLabel', type=d.T.string)]),
    withJobLabel(jobLabel): { spec+: { jobLabel: jobLabel } },
    '#withPipelineStages':: d.fn(help='"Pipeline stages for this pod. Pipeline stages support transforming and filtering log lines."', args=[d.arg(name='pipelineStages', type=d.T.array)]),
    withPipelineStages(pipelineStages): { spec+: { pipelineStages: if std.isArray(v=pipelineStages) then pipelineStages else [pipelineStages] } },
    '#withPipelineStagesMixin':: d.fn(help='"Pipeline stages for this pod. Pipeline stages support transforming and filtering log lines."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='pipelineStages', type=d.T.array)]),
    withPipelineStagesMixin(pipelineStages): { spec+: { pipelineStages+: if std.isArray(v=pipelineStages) then pipelineStages else [pipelineStages] } },
    '#withPodTargetLabels':: d.fn(help='"PodTargetLabels transfers labels on the Kubernetes Pod onto the target."', args=[d.arg(name='podTargetLabels', type=d.T.array)]),
    withPodTargetLabels(podTargetLabels): { spec+: { podTargetLabels: if std.isArray(v=podTargetLabels) then podTargetLabels else [podTargetLabels] } },
    '#withPodTargetLabelsMixin':: d.fn(help='"PodTargetLabels transfers labels on the Kubernetes Pod onto the target."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='podTargetLabels', type=d.T.array)]),
    withPodTargetLabelsMixin(podTargetLabels): { spec+: { podTargetLabels+: if std.isArray(v=podTargetLabels) then podTargetLabels else [podTargetLabels] } },
    '#withRelabelings':: d.fn(help='"RelabelConfigs to apply to logs before delivering. Grafana Agent Operator automatically adds relabelings for a few standard Kubernetes fields and replaces original scrape job name with __tmp_logs_job_name. \\n More info: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#relabel_configs"', args=[d.arg(name='relabelings', type=d.T.array)]),
    withRelabelings(relabelings): { spec+: { relabelings: if std.isArray(v=relabelings) then relabelings else [relabelings] } },
    '#withRelabelingsMixin':: d.fn(help='"RelabelConfigs to apply to logs before delivering. Grafana Agent Operator automatically adds relabelings for a few standard Kubernetes fields and replaces original scrape job name with __tmp_logs_job_name. \\n More info: https://grafana.com/docs/loki/latest/clients/promtail/configuration/#relabel_configs"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='relabelings', type=d.T.array)]),
    withRelabelingsMixin(relabelings): { spec+: { relabelings+: if std.isArray(v=relabelings) then relabelings else [relabelings] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
